FROM bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8

# Copy the custom entrypoint script into the image.
COPY custom-entrypoint.sh /usr/local/bin/custom-entrypoint.sh

# Make it executable.
RUN chmod +x /usr/local/bin/custom-entrypoint.sh

# Set the custom entrypoint.
ENTRYPOINT ["/usr/local/bin/custom-entrypoint.sh"]