FROM bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8

# Copy configuration files
COPY hadoop-config/core-site.xml /etc/hadoop/core-site.xml
COPY custom-entrypoint.sh /usr/local/bin/custom-entrypoint.sh

# Make the entrypoint script executable
RUN chmod +x /usr/local/bin/custom-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/custom-entrypoint.sh"]
